# This action executes name enforcer on a created branch within this repo
name: "Execute branch name enforcer"
on:
  create:

jobs:
  build:
    name: "Build and run the app"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get the source"
        uses: actions/checkout@v2
      - name: "Get node dependencies"
        run: npm ci
      - name: "build source"
        run: npm run build
      - name: "run app"
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          regex: "^(main)$;^(feature/[A-Z0-9]{2,6}-[0-9]{1,8}([-_]{1}[-_a-zA-Z]*)*)$;^((hotfix|bugfix)/[-_a-zA-Z0-9]*)$"
          delete_branch: "true"
              